### ISSUE TITLE
Debian package does not create configuration file

### ISSUE THREAD

**Issue by lmarien** [powerfolder/PF-CORE#3]
PowerFolder_Latest_amd64.deb downloaded today (19.2.20) does not produce a configuration file upon installation with sudo dpkg -i PowerFolder_Latest_amd64.deb rendering the client unable to connect or do anything useful. This is on Ubuntu 18.04.4 LTS bionic beaver.

I would post logs but none are generated. Folders ~/.PowerFolder and ~/.PowerFolder/logs are created successfully, but remain empty.

**Comment by sprajcpf** [comment]
Please create the PowerFolder.config manually under ~/.PowerFolder and add the following line:
verbose=true
