### ISSUE TITLE
Mavenize for security updates

### ISSUE THREAD

**Issue by habernal** [powerfolder/PF-CORE#4]
Disclosure: My university is using "HessenBox" which is a re-branded PowerFolder (but some older version).

I'm assuming the desktop client is based on PF-CORE, which scares me.

All packaged Java libraries are hard-coded (i.e. under lib) and most of them are more than two years old. I assume, many have been updated in the meantime to fix security issues.

If the project is Mavenized, dependencies might be checked for new security releases. Any plans in this respect? Or maintaining the dependencies?

**Comment by sprajcpf** [comment]
Yes. We plan to update the libraries in the future. Thank you also for the recommendation to mavenize.

**Comment by sprajcpf** [comment]
Since we are maintaining tickets in JIRA not on github we close this ticket

**Comment by habernal** [comment]
OK, I see, thanks. Why is there this github repo then? The latest releases are from 2019, the commits from 10 months ago, issues are not handled here. It's confusing and not really typical to opensource projects hosted at github. You might want to disable Issues (see the project setup), or even delete this repo rightaway.

**Comment by sprajcpf** [comment]
We use gitlab and jira for development, this is just a replication to make the source code available to public. Indeed the sync of git seems to be broken at the moment. Thanks for your recommendations
